receivers:
  otlp:
    protocols:
      grpc:

  solace:
    broker: [192.168.29.187:5672]
    max_unacknowledged: 500
    auth:
      sasl_plain:
        username: trace
        password: trace
    queue: queue://#telemetry-trace
    tls:
      insecure: true
      insecure_skip_verify: true

  kafka:
    brokers: [kafka:9092]
    topic: traces

exporters:
  logging:
    loglevel: "info"

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 500

  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
       receivers: [solace, kafka, otlp]
       processors: [batch, memory_limiter]
       exporters: [jaeger, logging]